# -*- mode: python ; coding: utf-8 -*-
import os

a = Analysis(
    ['core/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('config.json', '.'),
        ('rune_pages.json', '.'),
        (os.path.join('ui', 'theme', 'design_tokens.json'), os.path.join('ui', 'theme')),
    ],
    hiddenimports=[
        'keyboard',
        'services',
        'services.api_handler',
        'services.asset_manager',
        'services.automation',
        'ui',
        'ui.theme',
        'ui.theme.token_loader',
        'ui.ui_shared',
        'ui.tab_auto',
        'ui.tab_runes',
        'ui.tab_tools',
        'ui.components',
        'ui.components.factory',
        'ui.components.hover',
        'ui.components.color_utils',
        'ui.components.tooltip',
        'ui.layouts',
        'ui.layouts.auto',
        'ui.layouts.runes',
        'ui.layouts.tools',
        'utils',
        'utils.logger',
        'utils.path_utils',
        'PIL',
        'PIL._tkinter_finder',
        'psutil',
        'customtkinter',
        # --- requests / idna chain (PyInstaller misses these) ---
        'unicodedata',
        'idna',
        'idna.core',
        'idna.codec',
        'idna.idnadata',
        'idna.package_data',
        'charset_normalizer',
        'charset_normalizer.md__mypyc',
        'requests',
        'requests.packages',
        'urllib3',
        'urllib3.contrib',
        'certifi',
        'winreg',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AutoLock1.4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/app.ico'],
    uac_admin=True,
)
